FROM apache/airflow:2.9.0

USER root
RUN apt-get update && apt-get install -y gcc

USER airflow
RUN pip install \
    kafka-python \
    pandas \
    psycopg2-binary \
    python-dotenv \
    httpx \
    vaderSentiment