"""init tables

Revision ID: 6987e5820d57
Revises:
Create Date: 2026-05-21 17:54:56.725940

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6987e5820d57"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("app_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("developer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("publisher", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("is_indie", sa.Boolean(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("header_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("app_id"),
    )
    op.create_table(
        "genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "game_genres",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.INTEGER(), nullable=True),
        sa.Column("genre_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.INTEGER(), nullable=True),
        sa.Column("tag_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "genre_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("genre_id", sa.INTEGER(), nullable=True),
        sa.Column("avg_price", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("avg_positive_ratio", sa.NUMERIC(precision=5, scale=4), nullable=True),
        sa.Column("total_games", sa.Integer(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["genre_id"], ["genres.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hidden_gems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.INTEGER(), nullable=True),
        sa.Column("gem_score", sa.NUMERIC(precision=5, scale=4), nullable=True),
        sa.Column("positive_ratio", sa.NUMERIC(precision=5, scale=4), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("recent_positive_ratio", sa.NUMERIC(precision=5, scale=4), nullable=True),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("app_id", "calculated_at"),
    )
    op.create_table(
        "player_counts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.INTEGER(), nullable=True),
        sa.Column("player_count", sa.Integer(), nullable=False),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_player_counts_app_collected", "player_counts", ["app_id", "collected_at"], unique=False)
    op.create_table(
        "price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.INTEGER(), nullable=True),
        sa.Column("price", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("original_price", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("discount_rate", sa.NUMERIC(precision=5, scale=4), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_price_history_app_collected", "price_history", ["app_id", "collected_at"], unique=False)
    op.create_table(
        "review_texts",
        sa.Column("review_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("app_id", sa.INTEGER(), nullable=True),
        sa.Column("review_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("voted_up", sa.Boolean(), nullable=False),
        sa.Column("playtime_hours", sa.Integer(), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_table(
        "reviews_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app_id", sa.INTEGER(), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("positive_reviews", sa.Integer(), nullable=False),
        sa.Column("negative_reviews", sa.Integer(), nullable=False),
        sa.Column("positive_ratio", sa.NUMERIC(precision=5, scale=4), nullable=True),
        sa.Column("collected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["games.app_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_reviews_snapshot_app_collected", "reviews_snapshot", ["app_id", "collected_at"], unique=False)
    op.create_table(
        "review_analysis",
        sa.Column("review_id", sa.TEXT(), nullable=False),
        sa.Column("sentiment_score", sa.NUMERIC(precision=5, scale=4), nullable=True),
        sa.Column("toxicity", sa.NUMERIC(precision=5, scale=4), nullable=True),
        sa.Column("emotion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["review_id"], ["review_texts.review_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("review_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_analysis")
    op.drop_index("idx_reviews_snapshot_app_collected", table_name="reviews_snapshot")
    op.drop_table("reviews_snapshot")
    op.drop_table("review_texts")
    op.drop_index("idx_price_history_app_collected", table_name="price_history")
    op.drop_table("price_history")
    op.drop_index("idx_player_counts_app_collected", table_name="player_counts")
    op.drop_table("player_counts")
    op.drop_table("hidden_gems")
    op.drop_table("genre_stats")
    op.drop_table("game_tags")
    op.drop_table("game_genres")
    op.drop_table("tags")
    op.drop_table("genres")
    op.drop_table("games")
    # ### end Alembic commands ###
