"""add metacritic to games

Revision ID: bc8e3e444991
Revises: 6987e5820d57
Create Date: 2026-05-22 02:00:31.457615

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc8e3e444991"
down_revision: Union[str, Sequence[str], None] = "6987e5820d57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("games", sa.Column("metacritic_score", sa.Integer(), nullable=True))
    op.add_column("games", sa.Column("metacritic_url", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("games", "metacritic_url")
    op.drop_column("games", "metacritic_score")
    # ### end Alembic commands ###
